services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-app2
    volumes:
      - ./site-dino:/var/www/app
    ports:
      - "8084:80"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: symfony-db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dinos
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dinodb_clean.sql:/docker-entrypoint-initdb.d/dinodb_clean.sql:ro

volumes:
  db_data:
