# controllers:
#     resource: ../src/Controller/
#     type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

app_controllers:
    resource: ../src/Controller/
    type: attribute
    exclude: '../src/Controller/HomeController.php'